export function ddlTableQuery(schema: string, table: string): string {
  return `-- Generate CREATE TABLE DDL for "${schema}"."${table}"
SELECT 'CREATE TABLE "' || schemaname || '"."' || tablename || '" (' || E'\\n' ||
  string_agg('  "' || column_name || '" ' || data_type ||
    CASE WHEN character_maximum_length IS NOT NULL THEN '(' || character_maximum_length || ')' ELSE '' END ||
    CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END ||
    CASE WHEN column_default IS NOT NULL THEN ' DEFAULT ' || column_default ELSE '' END,
    ',' || E'\\n' ORDER BY ordinal_position) || E'\\n' || ');' AS ddl
FROM information_schema.columns c
JOIN pg_tables t ON t.schemaname = c.table_schema AND t.tablename = c.table_name
WHERE c.table_schema = '${schema}' AND c.table_name = '${table}'
GROUP BY schemaname, tablename;`;
}

export function ddlViewQuery(schema: string, view: string): string {
  return `-- View definition for "${schema}"."${view}"
SELECT pg_get_viewdef('"${schema}"."${view}"'::regclass, true) AS view_definition;`;
}

export function ddlFunctionQuery(schema: string, fnName: string): string {
  return `-- Function definition for "${schema}"."${fnName}"
SELECT pg_get_functiondef(p.oid) AS function_definition
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = '${schema}' AND p.proname = '${fnName}'
LIMIT 1;`;
}

/**
 * Starting points for creating an object, opened in a tab rather than run: a
 * form would have to cover a fraction of what CREATE accepts and would teach
 * its own limits, whereas a statement is complete, editable and leaves a trace
 * in the history.
 */
export function newTableTemplate(schema: string): string {
  return `CREATE TABLE "${schema}"."new_table" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);`;
}

export function newForeignTableTemplate(schema: string): string {
  return `-- Needs a foreign server: SELECT srvname FROM pg_foreign_server;
CREATE FOREIGN TABLE "${schema}"."new_foreign_table" (
  id   bigint,
  name text
)
SERVER server_name
OPTIONS (schema_name 'public', table_name 'remote_table');`;
}

export function newViewTemplate(schema: string): string {
  return `CREATE VIEW "${schema}"."new_view" AS
SELECT *
FROM "${schema}"."source_table"
WHERE true;`;
}

export function newMatViewTemplate(schema: string): string {
  return `CREATE MATERIALIZED VIEW "${schema}"."new_matview" AS
SELECT *
FROM "${schema}"."source_table"
WITH DATA;

-- A unique index is what REFRESH ... CONCURRENTLY needs
-- CREATE UNIQUE INDEX ON "${schema}"."new_matview" (id);`;
}

export function newSequenceTemplate(schema: string): string {
  return `CREATE SEQUENCE "${schema}"."new_sequence"
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 1;`;
}

export function newFunctionTemplate(schema: string): string {
  return `CREATE OR REPLACE FUNCTION "${schema}"."new_function"(p_id bigint)
RETURNS integer
LANGUAGE sql
STABLE
AS $$
  SELECT 1;
$$;`;
}

export function newProcedureTemplate(schema: string): string {
  return `CREATE OR REPLACE PROCEDURE "${schema}"."new_procedure"(p_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
  -- CALL "${schema}"."new_procedure"(1);
END;
$$;`;
}

export function newDataTypeTemplate(schema: string): string {
  return `CREATE TYPE "${schema}"."new_status" AS ENUM ('draft', 'active', 'archived');

-- Other kinds of type:
-- CREATE DOMAIN "${schema}"."new_email" AS text CHECK (VALUE ~ '@');
-- CREATE TYPE "${schema}"."new_address" AS (street text, city text);
-- CREATE TYPE "${schema}"."new_range" AS RANGE (subtype = numeric);`;
}

export function newTriggerFunctionTemplate(schema: string): string {
  return `CREATE OR REPLACE FUNCTION "${schema}"."new_trigger_function"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN NEW;
END;
$$;

-- Attach it to a table:
-- CREATE TRIGGER new_trigger BEFORE INSERT OR UPDATE ON "${schema}"."some_table"
--   FOR EACH ROW EXECUTE FUNCTION "${schema}"."new_trigger_function"();`;
}

export function newEventTriggerTemplate(): string {
  return `-- Event triggers fire on DDL anywhere in the database, and belong to
-- the database rather than to a schema.
CREATE OR REPLACE FUNCTION public.new_event_trigger_function()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE NOTICE 'ddl: %', tg_tag;
END;
$$;

CREATE EVENT TRIGGER new_event_trigger
  ON ddl_command_end
  EXECUTE FUNCTION public.new_event_trigger_function();`;
}

export function newDatabaseTemplate(): string {
  return `-- CREATE DATABASE cannot run inside a transaction
CREATE DATABASE "new_database"
  WITH ENCODING 'UTF8'
       TEMPLATE template0;`;
}

export function newSchemaTemplate(): string {
  return `CREATE SCHEMA "new_schema";`;
}
