import { quoteIdent } from "@/lib/sql-utils";
import type { DriverType } from "@/types";

/**
 * Starting points for creating an object, per engine.
 *
 * These are whole statements, not just quoted identifiers: an identity column,
 * a JSON type and a procedural language are spelled differently everywhere, so
 * a shared template with swapped quotes would still be wrong. Each engine gets
 * its own, and an engine with no template for an object simply does not offer
 * the menu entry — see the `objectTemplates` capability.
 *
 * The PostgreSQL versions live in `ddl-queries.ts`, alongside the ones only
 * PostgreSQL has.
 */

export function newTableTemplateFor(driver: DriverType, schema: string): string {
  const qi = (n: string) => quoteIdent(n, driver);

  if (driver === "MYSQL") {
    return `CREATE TABLE ${qi(schema)}.${qi("new_table")} (
  id         BIGINT AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;`;
  }

  if (driver === "SQLITE") {
    return `CREATE TABLE ${qi("new_table")} (
  -- INTEGER PRIMARY KEY is the rowid, which is what makes it auto-assign
  id         INTEGER PRIMARY KEY,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`;
  }

  return `CREATE TABLE ${qi(schema)}.${qi("new_table")} (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);`;
}

export function newViewTemplateFor(driver: DriverType, schema: string): string {
  const qi = (n: string) => quoteIdent(n, driver);

  if (driver === "SQLITE") {
    return `CREATE VIEW ${qi("new_view")} AS
SELECT *
FROM ${qi("source_table")}
WHERE 1 = 1;`;
  }

  const target = `${qi(schema)}.${qi("new_view")}`;
  const source = `${qi(schema)}.${qi("source_table")}`;
  return `CREATE VIEW ${target} AS
SELECT *
FROM ${source}
WHERE true;`;
}

export function newSchemaTemplateFor(driver: DriverType): string {
  // In MySQL a schema *is* a database, so the two statements are the same one.
  if (driver === "MYSQL") {
    return `CREATE DATABASE ${quoteIdent("new_database", driver)}
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;`;
  }
  return `CREATE SCHEMA ${quoteIdent("new_schema", driver)};`;
}

export function newDatabaseTemplateFor(driver: DriverType): string {
  if (driver === "MYSQL") {
    return newSchemaTemplateFor(driver);
  }
  return `-- CREATE DATABASE cannot run inside a transaction
CREATE DATABASE ${quoteIdent("new_database", driver)}
  WITH ENCODING 'UTF8'
       TEMPLATE template0;`;
}

export function newFunctionTemplateFor(driver: DriverType, schema: string): string {
  const qi = (n: string) => quoteIdent(n, driver);

  if (driver === "MYSQL") {
    // A single-statement body, deliberately: a BEGIN…END block needs the
    // delimiter changed, and DELIMITER is a directive of the mysql CLI rather
    // than SQL — the server would reject it if sent from here.
    return `CREATE FUNCTION ${qi(schema)}.${qi("new_function")}(p_id BIGINT)
RETURNS INT
DETERMINISTIC
READS SQL DATA
RETURN 1;

-- For a multi-statement body, run this in the mysql client, where DELIMITER
-- exists:
--   DELIMITER //
--   CREATE FUNCTION … BEGIN … END //
--   DELIMITER ;`;
  }

  return `CREATE OR REPLACE FUNCTION ${qi(schema)}.${qi("new_function")}(p_id bigint)
RETURNS integer
LANGUAGE sql
STABLE
AS $$
  SELECT 1;
$$;`;
}

export function newProcedureTemplateFor(driver: DriverType, schema: string): string {
  const qi = (n: string) => quoteIdent(n, driver);

  if (driver === "MYSQL") {
    // Single-statement body for the same reason as the function above.
    return `CREATE PROCEDURE ${qi(schema)}.${qi("new_procedure")}(IN p_id BIGINT)
SELECT p_id;

-- CALL ${qi(schema)}.${qi("new_procedure")}(1);
--
-- For a multi-statement body, use the mysql client, which has DELIMITER.`;
  }

  return `CREATE OR REPLACE PROCEDURE ${qi(schema)}.${qi("new_procedure")}(p_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
  -- CALL ${qi(schema)}.${qi("new_procedure")}(1);
END;
$$;`;
}
