import * as monaco from "monaco-editor";
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import { useUIStore } from "@/stores/ui-store";
import "@/monaco/setup";

/**
 * Read-only SQL with the same highlighting as the editor. Uses Monaco's
 * colorize(), which runs the SQL tokenizer against the active rsql theme
 * without instantiating an editor, so every static SQL surface in the app
 * (DDL, view definitions, function bodies, diffs) stays in one place.
 */
export function SqlCode({ code, className }: { code: string; className?: string }) {
  const theme = useUIStore((s) => s.theme);
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    monaco.editor.setTheme(theme === "light" ? "rsql-light" : "rsql-dark");
    monaco.editor
      .colorize(code, "sql", { tabSize: 2 })
      .then((result) => {
        if (active) setHtml(result);
      })
      .catch(() => {
        // Fall back to the plain text branch below
        if (active) setHtml(null);
      });
    return () => {
      active = false;
    };
  }, [code, theme]);

  const classes = cn(
    "monaco-editor font-mono text-code leading-relaxed whitespace-pre-wrap selection:bg-primary/20",
    className,
  );

  if (html === null) {
    return <pre className={classes}>{code}</pre>;
  }

  // colorize() output is generated by Monaco from `code`, not user-authored markup
  return (
    <pre
      className={classes}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: Monaco tokenizer output
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
